Repository Hicoding-Groupware/hicoding-back, pull requests merged in 2023-12, with the labels that each got.

#46 Feat/#42/day attendance
  src/main/java/com/hook/hicodingapi/attendance/domain/repository/AttendanceRepository.java
  src/main/java/com/hook/hicodingapi/attendance/dto/request/AttendanceRegistRequest.java
  src/main/java/com/hook/hicodingapi/attendance/dto/response/DailyAttendanceResponse.java
  src/main/java/com/hook/hicodingapi/attendance/dto/response/DayAttendanceResponse.java
  src/main/java/com/hook/hicodingapi/attendance/presentation/AttendanceController.java
  src/main/java/com/hook/hicodingapi/attendance/service/AttendanceService.java
  src/main/java/com/hook/hicodingapi/common/config/SecurityConfig.java
  src/main/java/com/hook/hicodingapi/course/domain/repository/MyLectureRepository.java
  src/main/java/com/hook/hicodingapi/course/presentation/MyLectureController.java
  src/main/java/com/hook/hicodingapi/course/service/MyLectureService.java
  src/main/java/com/hook/hicodingapi/jwt/CustomUser.java
  src/main/java/com/hook/hicodingapi/jwt/service/JwtService.java
  src/main/java/com/hook/hicodingapi/member/presentation/MemberController.java
  src/main/java/com/hook/hicodingapi/student/domain/Student.java
  src/main/java/com/hook/hicodingapi/student/domain/repository/StudentRepository.java
  src/main/java/com/hook/hicodingapi/student/presentation/StudentController.java
  src/main/java/com/hook/hicodingapi/student/service/StudentService.java
Labels: 🤍기능 개발

#52 2023-12-05 #49개인정보 업데이트 구현
  src/main/java/com/hook/hicodingapi/common/config/SecurityConfig.java
  src/main/java/com/hook/hicodingapi/login/filter/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/hook/hicodingapi/login/handler/LoginFailureHandler.java
  src/main/java/com/hook/hicodingapi/member/domain/Member.java
  src/main/java/com/hook/hicodingapi/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/hook/hicodingapi/member/presentation/LoginController.java
  src/main/java/com/hook/hicodingapi/member/presentation/MemberController.java
  src/main/java/com/hook/hicodingapi/member/service/MemberService.java
Labels: ❤ 리팩토링

#53 Feat/#26/student search
  src/main/java/com/hook/hicodingapi/common/config/SecurityConfig.java
  src/main/java/com/hook/hicodingapi/student/domain/repository/StudentRepository.java
  src/main/java/com/hook/hicodingapi/student/dto/response/StudentsRecordResponse.java
  src/main/java/com/hook/hicodingapi/student/presentation/StudentController.java
  src/main/java/com/hook/hicodingapi/student/service/StudentService.java
Labels: 🤍기능 개발

#55 feat/#26/수강생 등록 및 수정기능 완료
  src/main/java/com/hook/hicodingapi/student/domain/repository/StudentRepository.java
  src/main/java/com/hook/hicodingapi/student/dto/response/StudentDetailResponse.java
  src/main/java/com/hook/hicodingapi/student/presentation/StudentController.java
  src/main/java/com/hook/hicodingapi/student/service/StudentService.java
Labels: 🤍기능 개발

#58 2023-12-06 #49 개인정보 업데이트 구현
  src/main/java/com/hook/hicodingapi/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/hook/hicodingapi/member/service/MemberService.java
Labels: 🤍기능 개발

#61 feat/#42/엔드포인트 수정
  src/main/java/com/hook/hicodingapi/attendance/domain/repository/AttendanceRepository.java
  src/main/java/com/hook/hicodingapi/attendance/presentation/AttendanceController.java
  src/main/java/com/hook/hicodingapi/course/domain/repository/MyLectureRepository.java
  src/main/java/com/hook/hicodingapi/course/dto/resposne/DetailCourseLectureResponse.java
  src/main/java/com/hook/hicodingapi/course/dto/resposne/TeacherCourseResponse.java
  src/main/java/com/hook/hicodingapi/course/presentation/MyLectureController.java
  src/main/java/com/hook/hicodingapi/course/service/MyLectureService.java
Labels: ❤ 리팩토링, 🤍기능 개발

#63 Feat/#56/student management
  src/main/java/com/hook/hicodingapi/course/domain/repository/CourseRepository.java
  src/main/java/com/hook/hicodingapi/record/domain/repository/RecordRepository.java
  src/main/java/com/hook/hicodingapi/record/dto/response/RecordListResponse.java
  src/main/java/com/hook/hicodingapi/record/presentation/RecordController.java
  src/main/java/com/hook/hicodingapi/record/service/RecordService.java
  src/main/java/com/hook/hicodingapi/student/dto/response/StudentCourse.java
  src/main/java/com/hook/hicodingapi/student/dto/response/StudentCourseResponse.java
  src/main/java/com/hook/hicodingapi/student/presentation/StudentController.java
  src/main/java/com/hook/hicodingapi/student/service/StudentService.java
Labels: 🤍기능 개발

#65 Feature/#49 member update
  src/main/java/com/hook/hicodingapi/member/dto/response/ProfileResponse.java
  src/main/java/com/hook/hicodingapi/member/presentation/MemberController.java
  src/main/java/com/hook/hicodingapi/member/service/MemberService.java
Labels: 🤍기능 개발

#72 Feat/#56/student management
  src/main/java/com/hook/hicodingapi/common/config/SecurityConfig.java
  src/main/java/com/hook/hicodingapi/common/exception/FileStorageException.java
  src/main/java/com/hook/hicodingapi/common/exception/MyFileNotFoundException.java
  src/main/java/com/hook/hicodingapi/common/exception/ServerInternalException.java
  src/main/java/com/hook/hicodingapi/common/exception/type/ExceptionCode.java
  src/main/java/com/hook/hicodingapi/common/util/FileUploadUtils.java
  src/main/java/com/hook/hicodingapi/file/domain/File.java
  src/main/java/com/hook/hicodingapi/file/domain/repository/FileRepository.java
  src/main/java/com/hook/hicodingapi/file/domain/type/AccessStatus.java
  src/main/java/com/hook/hicodingapi/msg/Sample.java
  src/main/java/com/hook/hicodingapi/msg/domain/Message.java
  src/main/java/com/hook/hicodingapi/msg/domain/repository/MessageRepository.java
  src/main/java/com/hook/hicodingapi/msg/domain/type/ReadStatusType.java
  src/main/java/com/hook/hicodingapi/msg/domain/type/ReceiverStatusType.java
  src/main/java/com/hook/hicodingapi/msg/domain/type/SenderStatusType.java
  src/main/java/com/hook/hicodingapi/msg/dto/request/MessageCreateRequest.java
  src/main/java/com/hook/hicodingapi/msg/dto/response/MessageDetailReceiveResponse.java
  src/main/java/com/hook/hicodingapi/msg/dto/response/MessageDetailSendResponse.java
  src/main/java/com/hook/hicodingapi/msg/dto/response/MessageResponse.java
  src/main/java/com/hook/hicodingapi/msg/presentation/MessageController.java
  src/main/java/com/hook/hicodingapi/msg/service/MessageService.java
  src/main/java/com/hook/hicodingapi/student/presentation/StudentController.java
  src/main/java/com/hook/hicodingapi/student/service/StudentService.java
Labels: 🤍기능 개발

#79 Feat/#43/month attendance
  src/main/java/com/hook/hicodingapi/attendance/domain/repository/AttendanceRepository.java
  src/main/java/com/hook/hicodingapi/attendance/dto/request/AttendanceUpdateRequest.java
  src/main/java/com/hook/hicodingapi/attendance/dto/response/MonthAttendanceResponse.java
  src/main/java/com/hook/hicodingapi/attendance/presentation/AttendanceController.java
  src/main/java/com/hook/hicodingapi/attendance/service/AttendanceService.java
  src/main/java/com/hook/hicodingapi/common/exception/InvalidDateException.java
  src/main/java/com/hook/hicodingapi/common/exception/type/ExceptionCode.java
  src/main/java/com/hook/hicodingapi/course/domain/Course.java
  src/main/java/com/hook/hicodingapi/course/domain/repository/MyLectureRepository.java
  src/main/java/com/hook/hicodingapi/record/domain/Record.java
  src/main/java/com/hook/hicodingapi/student/domain/repository/StudentRepository.java
  src/main/java/com/hook/hicodingapi/student/service/StudentService.java
Labels: 🤍기능 개발

#81 feat/#73/쪽지기능구현
  src/main/java/com/hook/hicodingapi/main/message/presentation/MainMessageController.java
  src/main/java/com/hook/hicodingapi/main/message/response/MainMessageResponse.java
  src/main/java/com/hook/hicodingapi/main/message/service/MainMessageService.java
Labels: 🤍기능 개발

#82 Feat/#28/crud
  src/main/java/com/hook/hicodingapi/course/domain/repository/CourseRepository.java
  src/main/java/com/hook/hicodingapi/course/dto/resposne/CourseResponse.java
  src/main/java/com/hook/hicodingapi/course/presentation/CourseController.java
  src/main/java/com/hook/hicodingapi/course/service/CourseService.java
  src/main/java/com/hook/hicodingapi/lecture/domain/repository/LectureRepository.java
  src/main/java/com/hook/hicodingapi/lecture/dto/response/LectureDetailResponse.java
  src/main/java/com/hook/hicodingapi/lecture/presentation/LectureController.java
  src/main/java/com/hook/hicodingapi/lecture/service/LectureService.java
Labels: 🤍기능 개발

#84 Feature/#2 main page
  src/main/java/com/hook/hicodingapi/course/dto/resposne/TeacherCoursesResponse.java
  src/main/java/com/hook/hicodingapi/login/filter/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/hook/hicodingapi/main/course/presentation/MainCourseController.java
  src/main/java/com/hook/hicodingapi/main/course/service/MainCourseService.java
  src/main/java/com/hook/hicodingapi/main/myCourse/presentation/MainMyLectureController.java
  src/main/java/com/hook/hicodingapi/main/myCourse/service/MainMyLectureService.java
  src/main/java/com/hook/hicodingapi/member/domain/Member.java
  src/main/java/com/hook/hicodingapi/member/domain/repository/MemberRepository.java
  src/main/java/com/hook/hicodingapi/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/hook/hicodingapi/member/dto/response/ProfileResponse.java
  src/main/java/com/hook/hicodingapi/member/presentation/MemberController.java
  src/main/java/com/hook/hicodingapi/member/service/MemberService.java
Labels: ❤ 리팩토링

#85 Feat/#43/month attendance
  src/main/java/com/hook/hicodingapi/course/dto/resposne/DetailCourseLectureResponse.java
Labels: 🤍기능 개발

#87 Feat/#43/month attendance
  src/main/java/com/hook/hicodingapi/msg/presentation/MessageController.java
  src/main/java/com/hook/hicodingapi/student/service/StudentService.java
Labels: 💖 버그해결

#88 Feat/#43/month attendance
  src/main/java/com/hook/hicodingapi/attendance/presentation/AttendanceController.java
  src/main/java/com/hook/hicodingapi/attendance/service/AttendanceService.java
Labels: 💖 버그해결
